# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Streamlit frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry flake8
    - name: Install dependencies
      run: poetry install --with tests
    - name: Download browser
      run: poetry run playwright install chromium
    - name: Run Streamlit for tests
      run: BACKEND_URL="http://dzailz.su:8000/" poetry run streamlit run src/streamlit_frontend.py &
    - name: Test with pytest
      run: poetry run pytest --browser chromium
